In [11]:
import pandas as pd
import numpy as np
from datetime import datetime
import matplotlib.pyplot as plt

In [57]:
covid = pd.read_csv('/code/src/distribuicoes/caso_full.csv')
covid.dropna()
covid

,city,city_ibge_code,date,epidemiological_week,estimated_population,estimated_population_2019,is_last,is_repeated,last_available_confirmed,last_available_confirmed_per_100k_inhabitants,last_available_date,last_available_death_rate,last_available_deaths,order_for_place,place_type,state,new_confirmed,new_deaths
0,São Paulo,3550308.0,2020-02-25,202009,12325232.0,12252023.0,False,False,1,0.00811,2020-02-25,0.0000,0,1,city,SP,1,0
1,NaN,35.0,2020-02-25,202009,46289333.0,45919049.0,False,False,1,0.00216,2020-02-25,0.0000,0,1,state,SP,1,0
2,São Paulo,3550308.0,2020-02-26,202009,12325232.0,12252023.0,False,False,1,0.00811,2020-02-26,0.0000,0,2,city,SP,0,0
3,NaN,35.0,2020-02-26,202009,46289333.0,45919049.0,False,False,1,0.00216,2020-02-26,0.0000,0,2,state,SP,0,0
4,São Paulo,3550308.0,2020-02-27,202009,12325232.0,12252023.0,False,False,1,0.00811,2020-02-27,0.0000,0,3,city,SP,0,0
5,NaN,35.0,2020-02-27,202009,46289333.0,45919049.0,False,False,1,0.00216,2020-02-27,0.0000,0,3,state,SP,0,0
6,São Paulo,3550308.0,2020-02-28,202009,12325232.0,12252023.0,False,False,2,0.01623,2020-02-28,0.0000,0,4,city,SP,1,0
7,NaN,35.0,2020-02-28,202009,46289333.0,45919049.0,False,False,2,0.00432,2020-02-28,0.0000,0,4,state,SP,1,0
8,São Paulo,3550308.0,2020-02-29,202009,12325232.0,12252023.0,False,False,2,0.01623,2020-02-29,0.0000,0,5,city,SP,0,0
9,NaN,35.0,2020-02-29,202009,46289333.0,45919049.0,False,False,2,0.00432,2020-02-29,0.0000,0,5,state,SP,0,0
10,São Paulo,3550308.0,2020-03-01,202010,12325232.0,12252023.0,False,False,2,0.01623,2020-03-01,0.0000,0,6,city,SP,0,0
11,NaN,35.0,2020-03-01,202010,46289333.0,45919049.0,False,False,2,0.00432,2020-03-01,0.0000,0,6,state,SP,0,0
12,São Paulo,3550308.0,2020-03-02,202010,12325232.0,12252023.0,False,False,2,0.01623,2020-03-02,0.0000,0,7,city,SP,0,0
13,NaN,35.0,2020-03-02,202010,46289333.0,45919049.0,False,False,2,0.00432,2020-03-02,0.0000,0,7,state,SP,0,0
14,São Paulo,3550308.0,2020-03-03,202010,12325232.0,12252023.0,False,False,2,0.01623,2020-03-03,0.0000,0,8,city,SP,0,0
15,NaN,35.0,2020-03-03,202010,46289333.0,45919049.0,False,False,2,0.00432,2020-03-03,0.0000,0,8,state,SP,0,0
16,São Paulo,3550308.0,2020-03-04,202010,12325232.0,12252023.0,False,False,3,0.02434,2020-03-04,0.0000,0,9,city,SP,1,0
17,NaN,35.0,2020-03-04,202010,46289333.0,45919049.0,False,False,3,0.00648,2020-03-04,0.0000,0,9,state,SP,1,0
18,Barra Mansa,3300407.0,2020-03-05,202010,184833.0,184412.0,False,False,1,0.54103,2020-03-05,0.0000,0,1,city,RJ,1,0
19,São Paulo,3550308.0,2020-03-05,202010,12325232.0,12252023.0,False,False,6,0.04868,2020-03-05,0.0000,0,10,city,SP,3,0
20,NaN,32.0,2020-03-05,202010,4064052.0,4018650.0,False,False,1,0.02461,2020-03-05,0.0000,0,1,state,ES,1,0
21,NaN,33.0,2020-03-05,202010,17366189.0,17264943.0,False,False,1,0.00576,2020-03-05,0.0000,0,1,state,RJ,1,0
22,NaN,35.0,2020-03-05,202010,46289333.0,45919049.0,False,False,6,0.01296,2020-03-05,0.0000,0,10,state,SP,3,0
23,Feira de Santana,2910800.0,2020-03-06,202010,619609.0,614872.0,False,False,1,0.16139,2020-03-06,0.0000,0,1,city,BA,1,0
24,Barra Mansa,3300407.0,2020-03-06,202010,184833.0,184412.0,False,False,1,0.54103,2020-03-06,0.0000,0,2,city,RJ,0,0
25,Rio de Janeiro,3304557.0,2020-03-06,202010,6747815.0,6718903.0,False,False,1,0.01482,2020-03-06,0.0000,0,1,city,RJ,1,0
26,São Paulo,3550308.0,2020-03-06,202010,12325232.0,12252023.0,False,True,6,0.04868,2020-03-05,0.0000,0,11,city,SP,0,0
27,NaN,29.0,2020-03-06,202010,14930634.0,14873064.0,False,False,1,0.00670,2020-03-06,0.0000,0,1,state,BA,1,0
28,NaN,32.0,2020-03-06,202010,4064052.0,4018650.0,False,False,1,0.02461,2020-03-06,0.0000,0,2,state,ES,0,0
29,NaN,33.0,2020-03-06,202010,17366189.0,17264943.0,False,False,2,0.01152,2020-03-06,0.0000,0,2,state,RJ,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1517362,Tupiratins,1721307.0,2021-02-04,202105,2729.0,2671.0,False,True,40,1465.73837,2021-02-02,0.0000,0,258,city,TO,0,0
1517363,Wanderlândia,1722081.0,2021-02-04,202105,11734.0,11683.0,False,True,537,4576.44452,2021-02-02,0.0112,6,283,city,TO,0,0
1517364,Xambioá,1722107.0,2021-02-04,202105,11520.0,11540.0,False,True,1188,10312.50000,2021-02-02,0.0135,16,272,city,TO,0,0
1517365,NaN,12.0,2021-02-04,202105,894470.0,881935.0,True,False,49944,5583.64171,2021-02-04,0.0177,882,325,state,AC,397,3
1517366,NaN,27.0,2021-02-04,202105,3351543.0,3337357.0,True,False,119458,3564.26876,2021-02-04,0.0233,2780,334,state,AL,370,9
1517367,NaN,13.0,2021-02-04,202105,4207714.0,4144597.0,True,False,276551,6572.47617,2021-02-04,0.0315,8716,329,state,AM,2689,152
1517368,NaN,16.0,2021-02-04,202105,861773.0,845731.0,True,False,78213,9075.82391,2021-02-04,0.0137,1070,322,state,AP,224,1
1517369,NaN,29.0,2021-02-04,202105,14930634.0,14873064.0,True,False,599435,4014.79937,2021-02-04,0.0171,10255,336,state,BA,3295,39
1517370,NaN,23.0,2021-02-04,202105,9187103.0,9132078.0,True,False,379553,4131.36764,2021-02-04,0.0279,10577,326,state,CE,1362,21
1517371,NaN,53.0,2021-02-04,202105,3055149.0,3015268.0,True,False,279402,9145.28228,2021-02-04,0.0164,4591,335,state,DF,430,9
1517372,NaN,32.0,2021-02-04,202105,4064052.0,4018650.0,True,False,299224,7362.70107,2021-02-04,0.0199,5952,337,state,ES,1463,23
1517373,NaN,52.0,2021-02-04,202105,7113540.0,7018354.0,True,False,358350,5037.57623,2021-02-04,0.0214,7653,330,state,GO,2076,54
1517374,NaN,21.0,2021-02-04,202105,7114598.0,7075181.0,True,False,209085,2938.81678,2021-02-04,0.0227,4742,322,state,MA,361,12
1517375,NaN,31.0,2021-02-04,202105,21292666.0,21168791.0,True,False,756971,3555.07854,2021-02-04,0.0205,15499,334,state,MG,10052,184
1517376,NaN,50.0,2021-02-04,202105,2809394.0,2778986.0,False,True,163692,5826.59463,2021-02-03,0.0182,2972,328,state,MS,0,0
1517377,NaN,51.0,2021-02-04,202105,3526220.0,3484466.0,True,False,223054,6325.58377,2021-02-04,0.0235,5237,322,state,MT,1202,23
1517378,NaN,15.0,2021-02-04,202105,8690745.0,8602865.0,True,False,336453,3871.39422,2021-02-04,0.0229,7717,324,state,PA,1749,22
1517379,NaN,25.0,2021-02-04,202105,4039277.0,4018127.0,True,False,195482,4839.52945,2021-02-04,0.0210,4110,330,state,PB,963,14
1517380,NaN,26.0,2021-02-04,202105,9616621.0,9557071.0,True,False,266999,2776.43260,2021-02-04,0.0391,10430,330,state,PE,1650,31
1517381,NaN,22.0,2021-02-04,202105,3281480.0,3273227.0,True,False,161336,4916.56204,2021-02-04,0.0193,3112,323,state,PI,388,20
1517382,NaN,41.0,2021-02-04,202105,11516840.0,11433957.0,True,False,562057,4880.30571,2021-02-04,0.0182,10248,330,state,PR,3287,58
1517383,NaN,33.0,2021-02-04,202105,17366189.0,17264943.0,True,False,532377,3065.59488,2021-02-04,0.0570,30354,337,state,RJ,2852,182
1517384,NaN,24.0,2021-02-04,202105,3534165.0,3506853.0,False,True,143466,4059.40300,2021-02-03,0.0233,3339,330,state,RN,0,0
1517385,NaN,11.0,2021-02-04,202105,1796460.0,1777225.0,True,False,128743,7166.48297,2021-02-04,0.0180,2314,322,state,RO,1030,21
1517386,NaN,14.0,2021-02-04,202105,631181.0,605761.0,True,False,75288,11928.11571,2021-02-04,0.0118,886,321,state,RR,328,6
1517387,NaN,43.0,2021-02-04,202105,11422973.0,11377239.0,True,False,557125,4877.23292,2021-02-04,0.0195,10881,332,state,RS,2772,55
1517388,NaN,42.0,2021-02-04,202105,7252502.0,7164788.0,True,False,587428,8099.65995,2021-02-04,0.0110,6466,330,state,SC,2891,21
1517389,NaN,28.0,2021-02-04,202105,2318822.0,2298696.0,True,False,139611,6020.77262,2021-02-04,0.0201,2809,328,state,SE,388,8
1517390,NaN,35.0,2021-02-04,202105,46289333.0,45919049.0,True,False,1820941,3933.82424,2021-02-04,0.0297,53997,346,state,SP,13932,293
1517391,NaN,17.0,2021-02-04,202105,1590248.0,1572866.0,False,True,103616,6515.71327,2021-02-03,0.0135,1402,324,state,TO,0,0

In [50]:
cities = ["São Paulo", "Rio de Janeiro", "Belo Horizonte", "Fortaleza", "Porto Alegre", "Recife", "Brasília"]

covidDataGroupByCity = covid.groupby('city')['new_confirmed'].sum()

dfCovidDataGroupByCity = pd.DataFrame(covidDataGroupByCity)

dfCovidDataGroupByCity.reset_index(level=0, inplace=True)

dfCovidDataGroupByCity[dfCovidDataGroupByCity['city'].isin(cities)]

                city  new_confirmed
526   Belo Horizonte          92067
675         Brasília         244327
1709       Fortaleza         100404
3724    Porto Alegre          80404
3895          Recife          60338
4014  Rio de Janeiro         190327
4754       São Paulo         466172

In [55]:
covidDataGroupByCity = covid.groupby(['date', 'city'])['new_confirmed'].sum()

dfCovidDataGroupByCity = pd.DataFrame(covidDataGroupByCity)

#necessário dar o reset index 2 vezes para criar colunas corretamente
dfCovidDataGroupByCity.reset_index(level=0, inplace=True)
dfCovidDataGroupByCity.reset_index(level=0, inplace=True)

#renomeia a coluna de novos casos para casos confirmados
dfCovidDataGroupByCity.rename(columns={'new_confirmed':'casos confirmados'}, inplace=True)

citiesSelected = dfCovidDataGroupByCity[dfCovidDataGroupByCity['city'].isin(cities)]
citiesSelected

                   city        date  casos confirmados
0             São Paulo  2020-02-25                  1
1             São Paulo  2020-02-26                  0
2             São Paulo  2020-02-27                  0
3             São Paulo  2020-02-28                  1
4             São Paulo  2020-02-29                  0
5             São Paulo  2020-03-01                  0
6             São Paulo  2020-03-02                  0
7             São Paulo  2020-03-03                  0
8             São Paulo  2020-03-04                  1
10            São Paulo  2020-03-05                  3
13       Rio de Janeiro  2020-03-06                  1
14            São Paulo  2020-03-06                  0
16             Brasília  2020-03-07                  1
18       Rio de Janeiro  2020-03-07                  0
20            São Paulo  2020-03-07                  6
22             Brasília  2020-03-08                  0
26       Rio de Janeiro  2020-03-08                  1
28            São Paulo  2020-03-08                  3
30             Brasília  2020-03-09                  0
34       Rio de Janeiro  2020-03-09                  0
36            São Paulo  2020-03-09                  0
38             Brasília  2020-03-10                  0
43       Rio de Janeiro  2020-03-10                  0
45            São Paulo  2020-03-10                  3
47             Brasília  2020-03-11                  1
52         Porto Alegre  2020-03-11                  1
53       Rio de Janeiro  2020-03-11                  0
55            São Paulo  2020-03-11                 11
57             Brasília  2020-03-12                  0
71         Porto Alegre  2020-03-12                  1
...                 ...         ...                ...
1409886  Rio de Janeiro  2021-01-31                166
1410626       São Paulo  2021-01-31                  0
1411696  Belo Horizonte  2021-02-01                210
1411845        Brasília  2021-02-01                714
1412879       Fortaleza  2021-02-01                564
1414894    Porto Alegre  2021-02-01                757
1415065          Recife  2021-02-01                331
1415184  Rio de Janeiro  2021-02-01                111
1415924       São Paulo  2021-02-01                  0
1416994  Belo Horizonte  2021-02-02                  0
1417143        Brasília  2021-02-02                365
1418177       Fortaleza  2021-02-02                  0
1420192    Porto Alegre  2021-02-02                  0
1420363          Recife  2021-02-02                306
1420482  Rio de Janeiro  2021-02-02                569
1421222       São Paulo  2021-02-02                  0
1422292  Belo Horizonte  2021-02-03                270
1422441        Brasília  2021-02-03                586
1423475       Fortaleza  2021-02-03               1624
1425490    Porto Alegre  2021-02-03                  0
1425661          Recife  2021-02-03                468
1425780  Rio de Janeiro  2021-02-03                648
1426520       São Paulo  2021-02-03                  0
1427590  Belo Horizonte  2021-02-04               2073
1427739        Brasília  2021-02-04                  0
1428773       Fortaleza  2021-02-04                  0
1430788    Porto Alegre  2021-02-04                  0
1430959          Recife  2021-02-04                  0
1431078  Rio de Janeiro  2021-02-04                  0
1431818       São Paulo  2021-02-04                  0

[2330 rows x 3 columns]

In [56]:
#verificar se a soma bate com o groupby anterior
citiesSelected.groupby('city')['casos confirmados'].sum()

city
Belo Horizonte     92067
Brasília          244327
Fortaleza         100404
Porto Alegre       80404
Recife             60338
Rio de Janeiro    190327
São Paulo         466172
Name: casos confirmados, dtype: int64